export const ADD_VEHICLE = "ADD_NEW_VEHICLE";
export const REMOVE_VEHICLE = "REMOVE_VEHICLE";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const LOAD_CURRENT_VEHICLE = "LOAD_CURRENT_VEHICLE";
